<?php
/**
 * Created by PhpStorm.
 * User: maxin
 * Date: 8/25/2016
 * Time: 9:47 a.m.
 */

namespace Foggyline\Office\Model\ResourceModel;

class Employee extends \Magento\Eav\Model\Entity\AbstractEntity
{
    public function getEntityType()
    {
        if (empty($this->_type)) {
            $this->setType(\Foggyline\Office\Model\Employee::ENTITY);
        }

        return parent::getEntityType(); // TODO: Change the autogenerated stub
    }

    protected function _construct()
    {
        $this->_read = 'foggyline_office_employee_read';
        $this->_write = 'foggyline_office_employee_write';
    }
}